name: Deploy Theme and Plugins to WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy-theme:
    name: Deploy Theme via SFTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Theme via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          source: "./Theme/*"
          target: ${{ secrets.REMOTE_THEME_PATH }}

  deploy-plugins:
    name: Deploy Plugins via SFTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Plugins via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          source: "./Plugins/*"
          target: ${{ secrets.REMOTE_PLUGINS_PATH }}